# FROM ghcr.io/rocker-org/devcontainer/geospatial:4.4
FROM mcr.microsoft.com/devcontainers/cpp:1-ubuntu-24.04
# update indices

# install R
RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends software-properties-common dirmngr && \
    wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc && \
    add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/" && \
    apt-get install -y --no-install-recommends r-base

COPY .Rprofile .
RUN Rscript -e 'install.packages(c("xfun", "ggplot2", "data.table", "rmarkdown", "knitr"))'

RUN apt-get install -y --no-install-recommends libfontconfig1-dev libtiff-dev && \
    Rscript -e 'install.packages(c("languageserver", "httpgd"))'

RUN wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.6.42/quarto-1.6.42-linux-$(dpkg --print-architecture).deb && \
    dpkg -i quarto-1.6.42*

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
        software-properties-common \
        dirmngr \
        liblapack-dev \
        libblas-dev \
        gfortran 

# Add a build argument
RUN git clone https://github.com/UofUEpiBio/epiworldR && \
    cd epiworldR && git checkout fix-mixing &&  \
    R CMD INSTALL .

CMD ["bash"]
