# FROM ghcr.io/rocker-org/devcontainer/geospatial:4.4
FROM mcr.microsoft.com/devcontainers/cpp:1-ubuntu-24.04
# update indices

# install R
RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends software-properties-common dirmngr && \
    wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc && \
    add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/" && \
    apt-get install -y --no-install-recommends r-base

# Installing R2u for faster R package installation
RUN apt update -qq && apt install --yes --no-install-recommends \
    ca-certificates gnupg && \
    wget -q -O- https://eddelbuettel.github.io/r2u/assets/dirk_eddelbuettel_key.asc | tee -a /etc/apt/trusted.gpg.d/cranapt_key.asc && \
    echo "deb [arch=amd64] https://r2u.stat.illinois.edu/ubuntu jammy main" \
     > /etc/apt/sources.list.d/cranapt.list && \
     apt update -qq

RUN apt-get install -y r-cran-tidyverse r-cran-data.table

RUN echo "options(repos = c(CRAN = \"https://packagemanager.posit.co/cran/__linux__/noble/latest\"))" >> /etc/R/Rprofile.site 

RUN apt-get install -y r-cran-knitr \
    r-cran-rmarkdown r-cran-quarto 
    
RUN Rscript -e 'install.packages("xfun")'

# Installing quarto
RUN wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.6.42/quarto-1.6.42-linux-arm64.deb && \
    dpkg -i quarto-1.6.42-linux-arm64.deb && \
    rm quarto-1.6.42-linux-arm64.deb

CMD ["bash"]
