# Provo highschool in Utah county, Utah
# Davis highschool is also about 2,000
# Gains county (Texas outbreak) has 836 students.
# And so far, the total outbreak size is about 60.
Population size: 634
Contact rate: 2.380952
Quarantine willingness: 1
Incubation period: 12.0000
Days undetected: 2
Prodromal period: 3.0000
Quarantine days: -1
Rash period: 4.0000
Transmission rate: 0.9
Hospitalization rate: 0.2
Hospitalization days: 7
# Mean rate for last 5 years
Vaccination rate: 0.92
Vax improved recovery: 0.5000
Vax efficacy: 0.99
initial number of exposed: 1.0000
Seed: 2231
N days: 60
Replicates: 2000
Threads: 10
Isolation period: 4