name: Run all scenarios

on:
  push:

jobs:
  run_all:
    runs-on: ubuntu-latest
      
    container:
      image: rocker/tidyverse:4.4.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare scenarios
        run: |
          cd scenarios
          # Replacing the numbre of threads
          # with two
          sed -i 's/^Threads:.*/Threads: 1/g' */params.yaml

          # Replacing the number of runs
          sed -i 's/^Replicates:.*/Replicates: 100/g' */params.yaml
      
      - name: Run scenarios
        run: |
          cd scenarios
          make all -B



      