run: highschool.o highschool-params.yaml
	rm highschool-out/* && \
	./highschool.o highschool-params.yaml

highschool.o: highschool.cpp highschool.hpp
	g++ -std=c++14 highschool.cpp -o highschool.o



