---
format: gfm
title: Measles models
---

## Highschool model

```{r}
#| echo: true
system2("make", "highschool.o", wait = TRUE)
system2("./highschool.o", stdout = TRUE) |> cat(sep="\n")
```

In this particular run, we see:

- 1 seed case in a 1000 population.
- Contact rate: 10.0000.
- Contact tracing success rate: 0.9000.
- How many days back to trace: 14.0000.
- Incubation period: 5.0000.
- Max days in rash: 2.0000.
- Prodromal period: 4.0000.
- Quarantine days: 14.0000.
- Rash period: 4.0000.
- Transmission rate: 0.9500.
- Vaccination rate: 0.9000.
- Vaccine reduction in recovery rate: 0.5000.
- Vaccine reduction in susceptibility: 0.9800.

The final distribution (0 until day 60):

```
  - (0) Susceptible             :  999 -> 901
  - (1) Exposed                 :    1 -> 3
  - (2) Prodromal               :    0 -> 2
  - (3) Rash                    :    0 -> 1
  - (4) Isolated                :    0 -> 4
  - (5) Quarantined Exposed     :    0 -> 2
  - (6) Quarantined Susceptible :    0 -> 35
  - (7) Quarantined Prodromal   :    0 -> 5
  - (8) Recovered               :    0 -> 47
```

We can check that transitions between states looking at the transition matrix:

```
Transition Probabilities:
 - Susceptible              1.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00
 - Exposed                  0.00  0.68  0.19  0.00  0.00  0.11  0.00  0.02  0.00
 - Prodromal                0.00  0.00  0.70  0.26  0.00  0.00  0.00  0.04  0.00
 - Rash                     0.00  0.00  0.00  0.48  0.52  0.00  0.00  0.00  0.00
 - Isolated                 0.00  0.00  0.00  0.00  0.72  0.00  0.00  0.00  0.28
 - Quarantined Exposed      0.00  0.00  0.00  0.00  0.00  0.86  0.00  0.14  0.00
 - Quarantined Susceptible  0.08  0.00  0.00  0.00  0.00  0.00  0.92  0.00  0.00
 - Quarantined Infectious   0.00  0.00  0.05  0.00  0.22  0.00  0.00  0.73  0.00
 - Recovered  
```

From it, we see:

- Exposed can move to prodromal, quarantined exposed, or quarantined prodromal.
- Prodromal moves to Rash or Quarantined Prodromal (which is infectious).
- Rash moves to Isolated (and triggers contact tracing).
- Isolated moves to Recovered (full immunity).
- Quarantined Exposed either moves to quarantined infectious or to isolated. It can moved to exposed, but since the quarantine period is 14 days, we don't see any case.
- Quarantined Infectious moves to prodromal (if exits quarantine) or to isolated (if rash detected), in which case contact tracing is triggered.